### ISSUE TITLE
add a warning when running without root access

### ISSUE THREAD

**Issue by arthurlutz** [robots/ols-fwloader#3]
... does it need root access ? 

It just failed without root, then added sudo, worked, but tried again without sudo and it works now... 

```
arthur@black:~/local/ols-fwloader$ sudo ./src/ols_fwloader -S -f APP -P /dev/OpenLogicSniffer 
[sudo] password for arthur: 
Found OLS HW: 1, FW: 2.3, Boot: 2
Found flash: WINBOND W25X40 
done...
Passed self-test :) 
arthur@black:~/local/ols-fwloader$ ./src/ols_fwloader -S -f APP -P /dev/OpenLogicSniffer 
Found OLS HW: 1, FW: 2.3, Boot: 2
Found flash: WINBOND W25X40 
done...
Passed self-test :) 
```

**Comment by nickandrew** [comment]
I found I can write to /dev/ttyACM* as my normal user, but direct USB access (all bootloader operations) require root. Anyway I added a note about running as root into the README.md file.
