### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by ipatch** [robots/ols-fwloader#8]
Running macOS 10.13 here, and noticed I am unable to read the current firmware on my OpenBench Logic Sniffer using the command provided in the README

```shell
ols-fwloader -f BOOT -t HEX -R -r current-pic-firmware.hex
```

I end up with the following error message when trying to read the FW on the PIC to a local file.

```
Cannot claim USB device
Unable to set alternative interface
Other error - recv
```

FWIW, when plugging in the device with the jumper connected as described in the README, macOS doesn't appear to create a entry for the device located within `/dev`

**Comment by robots** [comment]
First of all, i am no expert in macos. Try to list usb devices (on linux lsusb). In boot mode, this device is HID device.
Second, have you tried to run it as root (its written in readme).
And you should probably use dangerous prototypes forum for support.

**Comment by ipatch** [comment]
forgot i even opened this issue a while back. 🤦‍♀️

spent some time this afternoon messing around with my _OLS_ and this particular program, _ols_fwloader_ and was able to read the contents of the PIC microcontroller along with the Winbond flash chip on the _OLS_ using the binary i built for macOS on macOS. 👍

I ended up having to sift through a couple of forum threads on the dangerousprototypes forum, and the command that allowed me to dump the current contents of the PIC in _hex_ and _bin_ are below

```shell
echo "dump in HEX format"
olsfwloader -f APP -P /dev/tty.usbmodem1411 -R -r dump.hex
echo "dump in BIN format"
ols_fwloader -f APP -P /dev/tty.usbmodem1411 -t BIN -R -r dump.bin
```

##

Output from dumping flash in hex

```shell
Found OLS HW: 1, FW: 3.0, Boot: 2
Found flash: WINBOND W25X40
Reading flash
................................................................
Writing file 'dump.hex'
```

##

💡 **The device had to be placed in update mode, ie. holding down the _update_ button while pressing the _reset_ button at the same time.**
